# -*- coding: utf-8 -*-
"""Copie de TP 2 - Additionnel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_356NodimJnirM5oGZozjlxy_W2Juis_

<center><img style="text-align:center; margin:0 auto" src="https://drive.google.com/uc?export=view&id=15uzPyvfgv3obSupxZAFHY21YA82yFs0M" title="Logo UMAB" alt="Logo UMAB" width="221" height="236">

<b>Université Abdelhamid Ibn Badis - Mostaganem
    <br>Faculté des Sciences Exactes et de l'Informatique
    <br>Département de Mathématiques et Informatique
    <br>Master IA4IOT
    <br>Programmation Avancée (Python)
    </b></center>

---

# <center>TP 02 - Exercices supplémentaires : Affichage, lecture, variables et débogage</center>
<b>Objectif</b> : L'objectif de ce second TP est de vous aider à vous familiariser avec le langage Python, à apprendre à bien utiliser les fonctions print et input pour l'affichage et la lecture. Vous ferez aussi vos premiers pas dans le débogage de code Python.  
**Exercices basés sur les fiches de TP proposés par <a href="https://edogdu.github.io/teaching.html">Erdogan Dogdu</a>.**

---
<center><b>Nom et prénoms : ** WISSAL MANSERI **


---

<b>Question 1 :</b> Affichez le type de la variable x à l'aide de la fonction type
"""

x = 13.4
#écrire votre code ici
type (x)

"""<b>Question 2 :</b> Affichez le type de la variable nom à l'aide de la fonction type"""

nom = 'Nour'
#écrire votre code ici
type (nom)

"""<b>Question 3 :</b> Corrigez le code ci-dessous afin d'obtenir le résultat attendu"""

x = '1.4'
y = 5
#Corrigez la ligne suivante
print(float(x) + y)

"""<b>Question 4 :</b> Corrigez le code ci-dessous"""

var = 'ma variable'
print(var)

"""<b>Question 5 :</b> Donnez l'expression pour l'équation ci-dessous et affichez la valeur obtenue en fonction des valeurs de x et y donnés

<img style="text-align:center; margin:0 auto" src="https://drive.google.com/uc?export=view&id=1cqq4YfDORfwyIWPIkmGPuyvW_n-cYd_E" title="équation" alt="équation" width="538" height="125">
"""

x = 5
z = 2
#écrire votre code ici
w= 2*x+2*x**2+z**-3
print(w)

"""<b>Question 6 :</b> Donnez le résultat affiché pour chacune des instructions (sans exécuter le code)
```python
print(5%2) # Affichage 1:
print(5//2) # Affichage 2:
print(5/2) # Affichage 3:
print(2**1**2) # Affichage 4:
print((2**1)**2) # Affichage 5:
print(2+3*4) # Affichage 6:
print(3//4) # Affichage 7:
```
"""

#Affichage 1: 1
#Affichage 2: 2
#Affichage 3: 2,5
#Affichage 4: 2
#Affichage 5: 4
#Affichage 6: 14
#Affichage 7: 0

"""<b>Question 7 :</b> Quel serait la valeur de x après l'exécution du code suivant
```python
a = 5
x = 4
x *= a + 1
```
"""

#Donnez la valeur de x sans exécuter le code
21

"""<b>Question 8 :</b> Écrivez le code qui permettrait d'obtenir le résultat suivant (sans utilisation de boucles)

<pre>
Entrez un entier : 5

5x0 = 0
5x1 = 5
5x2 = 10
5x3 = 15
5x4 = 20
5x5 = 25
5x6 = 30
5x7 = 35
5x8 = 40
5x9 = 45
</pre>


"""

#écrire votre code ici

W = int(input("please enter a number"))
i=0
print(W,"*" ,i,"=",i*W)
print(W,"*" ,i+1,"=",i+1*W)
print(W,"*" ,i+2,"=",i+2*W)
print(W,"*" ,i+3,"=",i+3*W)
print(W,"*" ,i+4,"=",i+4*W)
print(W,"*" ,i+5,"=",i+5*W)
print(W,"*" ,i+6,"=",i+6*W)
print(W,"*" ,i+7,"=",i+7*W)
print(W,"*" ,i+8,"=",i+8*W)
print(W,"*" ,i+9,"=",i+9*W)



"""**<center>N'oubliez pas d'évaluer ce chapitre en utilisant <a href="https://forms.gle/yqMqmoyKNs1o6FqC7">ce lien</a>. Merci pour votre collaboration !</br></center>**"""